import { ListChecks } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { ProjectFilter, readProjectParam } from "@/components/shared/project-filter";
import { ResultStatusBadge } from "@/components/shared/status-badges";
import { moduleLabel } from "@/components/test-runs/results-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requestDb } from "@/lib/server/db";
import type { TestResultStatus } from "@/types";

export const metadata: Metadata = { title: "Test Cases" };

const first = (v: string | string[] | undefined) => (Array.isArray(v) ? v[0] : v);

export default async function TestCasesPage({ searchParams }: PageProps<"/test-cases">) {
  const sp = await searchParams;
  const projectId = readProjectParam(sp.project);
  const testRunId = readProjectParam(first(sp.run));
  const db = await requestDb();
  const [cases, projects, run] = await Promise.all([
    db.testCases.list({ projectId, testRunId, limit: 1000 }),
    db.projects.list({ sort: "name" }),
    testRunId ? db.testRuns.getDetail(testRunId) : Promise.resolve(null),
  ]);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Test Cases"
        description={run ? `Cases generated and executed in "${run.name ?? `Run ${run.id.slice(0, 8)}`}".` : "Test cases generated by the engine for each page and module, with the verdicts recorded across browsers and viewports."}
        actions={run ? <Button variant="outline" asChild><Link href={`/test-runs/${run.id}`}>Back to run</Link></Button> : undefined}
      />
      {!run ? <ProjectFilter projects={projects} selected={projectId} basePath="/test-cases" /> : null}
      {cases.length === 0 ? (
        <EmptyState icon={ListChecks} title="No test cases yet" description="Test cases are created when a test run executes. Each case records the page, feature, element, steps and expected result." />
      ) : (
        <Card className="overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="hover:bg-transparent">
                <TableHead>ID</TableHead>
                <TableHead>Test case</TableHead>
                <TableHead className="hidden md:table-cell">Page</TableHead>
                <TableHead className="hidden lg:table-cell">Type</TableHead>
                <TableHead>Results</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {cases.map((c) => (
                <TableRow key={c.id} className="align-top">
                  <TableCell className="font-mono text-xs whitespace-nowrap">
                    {c.testRunId ? <Link href={`/test-runs/${c.testRunId}`} className="hover:underline">{c.code ?? "—"}</Link> : (c.code ?? "—")}
                  </TableCell>
                  <TableCell className="min-w-72">
                    <details>
                      <summary className="cursor-pointer list-none font-medium">{c.title}</summary>
                      <dl className="mt-2 grid gap-1.5 rounded-md border bg-muted/30 p-3 text-xs">
                        {[
                          ["Section", c.section],
                          ["Feature", c.feature],
                          ["Element", c.element],
                          ["Preconditions", c.preconditions],
                          ["Test data", c.testData],
                          ["Expected", c.expectedResult],
                        ]
                          .filter(([, v]) => v)
                          .map(([k, v]) => (
                            <div key={k} className="grid gap-0.5 sm:grid-cols-[100px_1fr]">
                              <dt className="text-muted-foreground">{k}</dt>
                              <dd className="break-words">{v}</dd>
                            </div>
                          ))}
                        {c.steps.length ? (
                          <div className="grid gap-0.5 sm:grid-cols-[100px_1fr]">
                            <dt className="text-muted-foreground">Steps</dt>
                            <dd><ol className="list-decimal pl-4">{c.steps.map((s, i) => <li key={i}>{s}</li>)}</ol></dd>
                          </div>
                        ) : null}
                      </dl>
                    </details>
                    <p className="mt-0.5 text-xs text-muted-foreground">{c.projectName}</p>
                  </TableCell>
                  <TableCell className="hidden max-w-56 truncate font-mono text-xs md:table-cell">{c.pageUrl ?? "—"}</TableCell>
                  <TableCell className="hidden lg:table-cell">
                    <div className="flex flex-wrap gap-1">
                      <Badge variant="secondary">{moduleLabel(c.module)}</Badge>
                      {c.scenarioType && c.scenarioType !== "FUNCTIONAL" ? <Badge variant="outline">{c.scenarioType.charAt(0) + c.scenarioType.slice(1).toLowerCase()}</Badge> : null}
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex flex-wrap gap-1">
                      {c.resultSummary.length
                        ? c.resultSummary.map((s) => (
                            <span key={s.status} className="inline-flex items-center gap-1">
                              <ResultStatusBadge status={s.status as TestResultStatus} />
                              {s.count > 1 ? <span className="text-xs text-muted-foreground">×{s.count}</span> : null}
                            </span>
                          ))
                        : <span className="text-xs text-muted-foreground">No results</span>}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}
    </div>
  );
}
